# Generated by Django 5.2.17 on 2026-09-28 20:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('not_modified', 'Not modified'), ('failed', 'Failed')], default='running', max_length=20)),
                ('total_in_source', models.PositiveIntegerField(default=0)),
                ('new_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('closed_count', models.PositiveIntegerField(default=0)),
                ('reopened_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etag', models.CharField(blank=True, max_length=200)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'sync state',
                'verbose_name_plural': 'sync state',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text="The source's `id` (a UUID).", max_length=64, unique=True)),
                ('company', models.CharField(db_index=True, max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('locations', models.JSONField(default=list, help_text='List of strings, e.g. ["SF", "Remote in USA"].')),
                ('url', models.URLField(max_length=1000)),
                ('company_url', models.URLField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, help_text='Normalized during sync.', max_length=50)),
                ('terms', models.JSONField(default=list)),
                ('sponsorship', models.CharField(blank=True, max_length=100)),
                ('degrees', models.JSONField(default=list)),
                ('source', models.CharField(blank=True, help_text='Who added the posting upstream.', max_length=100)),
                ('date_posted', models.DateTimeField(db_index=True)),
                ('date_updated', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(default=dict, help_text='The original source entry, for debugging.')),
            ],
            options={
                'ordering': ['-date_posted'],
                'indexes': [models.Index(fields=['is_active', '-date_posted'], name='listing_active_posted_idx')],
            },
        ),
    ]
